"""
concat_csv.py
=============
Concatenates two simulation CSV files into a single continuous dataset.

Author:
    - Ulrich Melade

What it does:
    Reads two CSV files produced by simulator.py (separator '|'), shifts the
    time/point column 't' of the second file so that it starts right after the
    end of the first one, then writes the merged file. Useful to build long
    scenarios (e.g. 3 nominal days + 3 leak days -> one 6-day dataset).
    Both inputs must have exactly the same columns (same monitored pipes),
    otherwise the script aborts without writing anything.

What to modify (in __main__) and its effect:
    - file1_path  : first CSV; kept as-is, it defines the time origin.
    - file2_path  : second CSV; its 't' column is shifted automatically.
    - output_path : path of the merged CSV.
"""

import pandas as pd
import numpy as np
import os


def concat_csvs(file1, file2, output_file):
    """
    Concatenates two CSV files generated by the simulator.
    Automatically adjusts the 't' column (time or points) of the second file
    so it seamlessly follows the end of the first file.
    """
    print(f"Reading the first file: {file1}")
    df1 = pd.read_csv(file1, sep="|")

    print(f"Reading the second file: {file2}")
    df2 = pd.read_csv(file2, sep="|")

    # Ensure columns match
    if list(df1.columns) != list(df2.columns):
        print("Error: The two files do not have the exact same columns.")
        return

    # Calculate offset for the 't' column
    if len(df1) > 0 and len(df2) > 1:
        last_t_df1 = df1["t"].iloc[-1]
        first_t_df2 = df2["t"].iloc[0]
        step = df2["t"].iloc[1] - df2["t"].iloc[0]

        offset = last_t_df1 + step - first_t_df2

        print(f"Adjusting time/points for the 2nd file (Offset +{offset})...")
        df2["t"] = df2["t"] + offset

    # Concatenate
    print("Concatenating...")
    df_combined = pd.concat([df1, df2], ignore_index=True)

    # Save
    print(f"Saving to: {output_file}")

    # If 't' is integer type (like points), ensure it stays integer
    if df1["t"].dtype == np.int64 or df1["t"].dtype == np.int32:
        df_combined["t"] = df_combined["t"].astype(int)
    else:
        df_combined["t"] = df_combined["t"].round(1)

    df_combined.to_csv(output_file, sep="|", index=False, float_format="%.6f")
    print("Completed successfully!")


if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.abspath(__file__))

    # By default, concatenate two existing files (to be adapted)
    file1_path = os.path.join(base_dir, "Network", "Scenario", "3d_nominal.csv")
    file2_path = os.path.join(base_dir, "Network", "Scenario", "3d_leak.csv")
    output_path = os.path.join(base_dir, "Network", "Scenario", "6d_combined.csv")

    concat_csvs(file1_path, file2_path, output_path)
