Temporal downsampling of a simulation CSV.

Author:
    - Ulrich Melade

What it does:
    Loads a CSV produced by simulator.py (separator '|'), groups the rows into
    fixed windows of freq_min minutes and aggregates each window: mean for the
    numeric (sensor) columns, event-aware logic for the text columns
    ('yd' -> 'yes' if any 'yes' in the window, 'ud' -> last active event,
    others -> last value). The 't' column is finally converted to consecutive
    point indices (0, 1, 2, ...). The output keeps exactly the same column
    layout as the input, so it stays compatible with the other tools
    (export_plots.py, concat_csv.py, HeMu).

What to modify (in __main__) and its effect:
    - input_path / output_path : source and destination CSV files.
    - freq_min                 : aggregation window in minutes. A larger value
                                 gives fewer rows and smoother curves, but
                                 less temporal detail (short events may be
                                 averaged out).
"""

import pandas as pd
import numpy as np
import os

def resample_csv(input_file, output_file, freq_min=3):
    """
    Resamples the CSV file generated by the simulator.
    By default, aggregates the data every 30 minutes.
    Keeps the same format (separator |, identical columns, empty cell for NaN).
    """
    print(f"Loading {input_file}...")
    if not os.path.exists(input_file):
        print(f"Error: File {input_file} does not exist.")
        return
        
    df = pd.read_csv(input_file, sep='|')
    original_columns = df.columns.tolist()
    
    # Identify sensor/model data columns
    data_cols = [c for c in df.columns if c.startswith('x_') or c.startswith('yc_')]
    
    # Empty cells are already read as NaN by pandas — no conversion needed
    
    # Convert 't' (seconds) to datetime to use pandas resample function
    df['datetime'] = pd.to_datetime(df['t'], unit='s')
    df.set_index('datetime', inplace=True)
    
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()
    
    # Aggregation dictionary
    agg_dict = {col: 'mean' for col in numeric_cols}
    
    for col in cat_cols:
        if col == 'yd':
            # If there was a 'yes' event in the interval, keep 'yes'
            agg_dict[col] = lambda x: 'yes' if (x == 'yes').any() else 'no'
        elif col == 'ud':
            # Keep the last active event in the interval, or 'no'
            agg_dict[col] = lambda x: x[x != 'no'].iloc[-1] if len(x[x != 'no']) > 0 else 'no'
        else:
            agg_dict[col] = 'last'
            
    print(f"Resampling every {freq_min} minutes (rolling mean)...")
    df_resampled = df.resample(f'{freq_min}min').agg(agg_dict)
    
    # Drop empty rows generated by resample if simulation was cut
    df_resampled.dropna(subset=['t'], inplace=True)
    
    # NaNs remain empty cells in the CSV (no -1.0 sentinel)
    
    # Format 't' to match exactly the start of the interval (0, 1800, 3600...)
    df_resampled['t'] = (df_resampled.index - pd.Timestamp('1970-01-01')).total_seconds()
    df_resampled['t'] = df_resampled['t'].round(1)
    
    # Reorder columns to perfectly match the original format
    df_resampled = df_resampled[original_columns]
    # Transform time to 'points' (0, 1, 2, 3...)
    df_resampled['t'] = (df_resampled['t'] / (freq_min * 60)).astype(int)
    
    print(f"Saving to {output_file}...")
    df_resampled.to_csv(output_file, sep='|', index=False, float_format='%.6f')
    print("Completed successfully!")

if __name__ == "__main__":
    # Default paths
    base_dir = os.path.dirname(os.path.abspath(__file__))
    input_path = os.path.join(base_dir, 'reseau', 'Scenario 5', 'export_3j.csv')
    output_path = os.path.join(base_dir, 'reseau', 'Scenario 5', 'export_4j.csv')
    
    resample_csv(input_path, output_path, freq_min=3)
